# OverlayFont.cmake - the dev overlay's font, fetched and compiled into the mod.
#
# Dear ImGui 1.91.5 embeds only ProggyClean, a pixel font whose stems land on the pixel
# grid at 13px and at exact multiples of it, so any size in between comes out blurred.
# ProggyForever is the scalable companion drawn to match it, and ImGui 1.92 uses it as its
# own default above 15px. Fetched rather than checked in so its licence stages into the
# drop-in through Notices.cmake like every other dependency's.
#
# The TTF becomes a byte array at configure time (no host tool, so the cross builds need
# nothing extra). Sets MTHAP_OVERLAY_FONT_SOURCE, which src/pal compiles into mthap_pal,
# so this must be included before that subdirectory is added.

include_guard(GLOBAL)
include(FetchContent)

FetchContent_Declare(
    proggyforever
    GIT_REPOSITORY https://github.com/ocornut/proggyforever.git
    GIT_TAG        f8868ba43bb42c4d88454d03ad81cbd139789f72
)
FetchContent_MakeAvailable(proggyforever)

set(_font_ttf "${proggyforever_SOURCE_DIR}/ProggyForever-Regular.ttf")
set(_font_cpp "${CMAKE_BINARY_DIR}/generated/overlay_font_data.cpp")

if(NOT EXISTS "${_font_ttf}")
    message(FATAL_ERROR "overlay font: ${_font_ttf} missing from the fetched checkout")
endif()

file(READ "${_font_ttf}" _font_hex HEX)
string(LENGTH "${_font_hex}" _font_hex_length)
math(EXPR _font_bytes "${_font_hex_length} / 2")
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _font_array "${_font_hex}")

# One long initializer line. CMake's regex has no repetition quantifier to wrap the bytes
# with, and generated data is read by the compiler alone.
file(WRITE "${_font_cpp}"
"// Generated by cmake/OverlayFont.cmake from ProggyForever-Regular.ttf. Do not edit.\n"
"// MIT license / Copyright (c) 2026 Disco Hello, Copyright (c) 2019,2023 Tristan Grimmer\n"
"\n"
"#include \"pal/overlay_font.hpp\"\n"
"\n"
"namespace pal\n"
"{\n"
"\n"
"namespace\n"
"{\n"
"const unsigned char kOverlayFontTtf[${_font_bytes}] = {${_font_array}};\n"
"} // namespace\n"
"\n"
"const void *overlay_font_ttf(int *out_size)\n"
"{\n"
"    *out_size = static_cast<int>(sizeof(kOverlayFontTtf));\n"
"    return kOverlayFontTtf;\n"
"}\n"
"\n"
"} // namespace pal\n")

set(MTHAP_OVERLAY_FONT_SOURCE "${_font_cpp}")
message(STATUS "Overlay font: ProggyForever-Regular.ttf (${_font_bytes} bytes) -> ${_font_cpp}")
